name: Build Resume

# Trigger the workflow manually or on push to specific files
on:
  workflow_dispatch: # Allows manual triggering
  push:
    paths:
      - 'resume.md'                  # Trigger on changes to resume.md
      - 'resume.yml'                 # Trigger on changes to resume.yml
      - '.github/workflows/build-resume.yml'  # Trigger on changes to this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install Pandoc and broader LaTeX dependencies
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra

      # Install Python dependencies
      - name: Install Python packages
        run: |
          pip install pypandoc PyYAML

      # Generate PDF and DOCX from Markdown using a Python script
      - name: Generate Resume Files
        run: |
          python - <<EOF
          import pypandoc
          import yaml
          import os
          import time

          # Load the config file
          with open('resume.yml', 'r') as config_file:
              config = yaml.safe_load(config_file)

          source_file = config['source']
          pdf_output = config['output']['pdf']
          docx_output = config['output']['word']
          font_size = config['output']['format']['font-size']
          margins = config['output']['format']['margins']

          # Ensure we're working in the current directory
          current_dir = os.getcwd()
          pdf_path = os.path.join(current_dir, pdf_output)
          docx_path = os.path.join(current_dir, docx_output)

          # Pandoc arguments for PDF
          pdf_args = [
              '--pdf-engine=pdflatex',
              f'-V geometry:margin={margins}in',
              f'-V fontsize={font_size}pt'
          ]
          try:
              pypandoc.convert_file(source_file, 'pdf', outputfile=pdf_path, extra_args=pdf_args)
              if os.path.exists(pdf_path):
                  print(f"PDF generated at: {pdf_path} (size: {os.path.getsize(pdf_path)} bytes)")
              else:
                  print(f"PDF conversion succeeded but file not found at: {pdf_path}")
          except Exception as e:
              print(f"PDF conversion failed: {e}")

          # Pandoc arguments for DOCX with verbose output
          docx_args = [
              '--verbose',  # Add detailed output for debugging
              '--reference-doc=custom-reference.docx' if 'custom-reference.docx' in os.listdir() else ''
          ]
          try:
              output = pypandoc.convert_file(source_file, 'docx', outputfile=docx_path, extra_args=docx_args)
              print(f"DOCX conversion output: {output}")
              if os.path.exists(docx_path) and os.path.getsize(docx_path) > 0:
                  print(f"DOCX generated at: {docx_path} (size: {os.path.getsize(docx_path)} bytes)")
              else:
                  print(f"DOCX conversion succeeded but file empty or not found at: {docx_path}")
          except Exception as e:
              print(f"DOCX conversion failed: {e}")

          # Brief delay to ensure files are fully written
          time.sleep(1)

          # Debug: List files and their sizes
          print("Files in current directory:")
          for file in os.listdir(current_dir):
              file_path = os.path.join(current_dir, file)
              if os.path.isfile(file_path):
                  print(f" - {file} (size: {os.path.getsize(file_path)} bytes)")
              else:
                  print(f" - {file} (directory)")
          EOF

      # Upload PDF as raw file (alternative approach)
      - name: Upload PDF Artifact
        run: |
          if [ -f "resume.pdf" ]; then
            echo "Uploading resume.pdf as raw file"
            gh release upload --clobber latest resume.pdf || gh release create --latest latest resume.pdf
          else
            echo "Error: resume.pdf not found"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload DOCX as raw file (alternative approach)
      - name: Upload DOCX Artifact
        run: |
          if [ -f "resume.docx" ] && [ $(stat -c %s resume.docx) -gt 0 ]; then
            echo "Uploading resume.docx as raw file"
            gh release upload --clobber latest resume.docx || gh release create --latest latest resume.docx
          else
            echo "Error: resume.docx not found or empty"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}