name: Build Resume

# Trigger the workflow manually or on push to specific files
on:
  workflow_dispatch: # Allows manual triggering
  push:
    paths:
      - 'resume.md'                  # Trigger on changes to resume.md
      - 'resume.yml'                 # Trigger on changes to resume.yml
      - '.github/workflows/build-resume.yml'  # Trigger on changes to this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install Pandoc and broader LaTeX dependencies
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra

      # Install Python dependencies
      - name: Install Python packages
        run: |
          pip install pypandoc PyYAML

      # Generate PDF using Python script
      - name: Generate PDF File
        run: |
          python - <<EOF
          import pypandoc
          import yaml
          import os
          import time

          # Load the config file
          with open('resume.yml', 'r') as config_file:
              config = yaml.safe_load(config_file)

          source_file = config['source']
          pdf_output = config['output']['pdf']
          font_size = config['output']['format']['font-size']
          margins = config['output']['format']['margins']

          # Ensure we're working in the current directory
          current_dir = os.getcwd()
          pdf_path = os.path.join(current_dir, pdf_output)

          # Pandoc arguments for PDF
          pdf_args = [
              '--pdf-engine=pdflatex',
              f'-V geometry:margin={margins}in',
              f'-V fontsize={font_size}pt'
          ]
          try:
              pypandoc.convert_file(source_file, 'pdf', outputfile=pdf_path, extra_args=pdf_args)
              if os.path.exists(pdf_path):
                  print(f"PDF generated at: {pdf_path} (size: {os.path.getsize(pdf_path)} bytes)")
              else:
                  print(f"PDF conversion succeeded but file not found at: {pdf_path}")
          except Exception as e:
              print(f"PDF conversion failed: {e}")

          time.sleep(1)  # Ensure file is written
          EOF

      # Generate DOCX using direct Pandoc command
      - name: Generate DOCX File
        run: |
          echo "Running Pandoc directly for DOCX conversion..."
          pandoc resume.md -o resume.docx --verbose
          if [ -f "resume.docx" ] && [ $(stat -c %s resume.docx) -gt 0 ]; then
            echo "DOCX generated at: $(pwd)/resume.docx (size: $(stat -c %s resume.docx) bytes)"
          else
            echo "DOCX conversion failed or produced empty file"
            ls -lh
            exit 1
          fi

      # Debug: List all files
      - name: Verify Files Exist
        run: |
          ls -lh
          if [ -f "resume.pdf" ]; then echo "PDF exists"; else echo "PDF missing"; exit 1; fi
          if [ -f "resume.docx" ] && [ $(stat -c %s resume.docx) -gt 0 ]; then echo "DOCX exists and non-empty"; else echo "DOCX missing or empty"; exit 1; fi

      # Upload PDF as artifact (ZIP for now)
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf

      # Upload DOCX as artifact (ZIP for now)
      - name: Upload DOCX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-docx
          path: resume.docx